name: 每小时自动更新直播源

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 * * * *'

permissions:
  contents: write   # 关键：给Action读写仓库权限

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: 拉取代码
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 配置Git安全目录
        run: git config --global safe.directory "$GITHUB_WORKSPACE"

      - name: 安装Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: 安装依赖
        run: pip install requests

      - name: 运行爬取脚本
        run: python main.py

      - name: 提交并推送更新
        run: |
          git config --global user.name "AutoBot"
          git config --global user.email "bot@github.com"
          git add .
          git commit -m "Auto update live.txt $(date +'%Y-%m-%d %H:%M')" || echo "无文件更新，跳过提交"
          git push
